"""initial core schema

Revision ID: 35f016cf814b
Revises: 
Create Date: 2026-09-18 20:05:19.878945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from app.models.document_chunk import EMBEDDING_DIMENSIONS

revision: str = '35f016cf814b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # auth.users is provided by Supabase. Ensure the schema and table exist so
    # this migration is reproducible on non-Supabase Postgres (CI, local); both
    # statements are no-ops against a real Supabase database.
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE TABLE IF NOT EXISTS auth.users (id uuid PRIMARY KEY)")

    op.create_table('document_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=EMBEDDING_DIMENSIONS), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunk'))
    )
    op.create_index('ix_document_chunk_embedding_hnsw', 'document_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='citizen', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('citizen', 'operator', 'admin')", name=op.f('ck_profile_role_valid')),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='fk_profile_id_auth_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='fk_audit_log_profile_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_profile_id'), 'audit_log', ['profile_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='fk_document_profile_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_profile_id'), 'document', ['profile_id'], unique=False)
    op.create_table('ocr_extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('masked_value', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0.00 AND confidence <= 1.00', name=op.f('ck_ocr_extraction_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name='fk_ocr_extraction_document_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ocr_extraction'))
    )
    op.create_index(op.f('ix_ocr_extraction_document_id'), 'ocr_extraction', ['document_id'], unique=False)

    # Row Level Security: default-deny for anon/authenticated access via the
    # Supabase API until owner-scoped policies are designed.
    # TODO(rbac): add policies (profile.id = auth.uid(); document.profile_id =
    # auth.uid(); audit_log.profile_id = auth.uid(); join-through policies for
    # ocr_extraction/document_chunk) and block client-side role changes.
    op.execute("ALTER TABLE profile ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ocr_extraction ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE document_chunk ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_extraction_document_id'), table_name='ocr_extraction')
    op.drop_table('ocr_extraction')
    op.drop_index(op.f('ix_document_profile_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_audit_log_profile_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('profile')
    op.drop_index('ix_document_chunk_embedding_hnsw', table_name='document_chunk', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
